{% set name = "statsforecast" %}
{% set version = "2.0.2" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/statsforecast-{{ version }}.tar.gz
  sha256: fd790fd4fe98f6e5571ee9f3a3d77bdffa7d57702b68a7657675be3864b77d46

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build }}

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pybind11
    - setuptools
  run:
    - python
    - cloudpickle
    - coreforecast >=0.0.12
    - fugue >=0.9.0
    - matplotlib-base
    - numba >=0.55.0
    - numpy >=1.21.6
    - pandas >=1.3.5
    - scipy >=1.7.3,<1.16.0
    - statsmodels >=0.13.2
    - threadpoolctl >=3
    - tqdm
    - utilsforecast >=0.1.4

test:
  imports:
    - statsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/statsforecast/
  summary: Time series forecasting suite using statistical models
  license: Apache-2.0
  license_file: LICENSE
  description: |
    **StatsForecast** offers a collection of widely used univariate time series forecasting
    models, including exponential smoothing and automatic `ARIMA` modeling optimized for
    high performance using `numba`.

    - [Getting started](https://nixtlaverse.nixtla.io/statsforecast/docs/getting-started/getting_started_short.html)
    - [Installation](https://nixtlaverse.nixtla.io/statsforecast/docs/getting-started/installation.html)

    PyPI: [https://pypi.org/project/statsforecast/](https://pypi.org/project/statsforecast/)

  doc_url: https://nixtlaverse.nixtla.io/statsforecast/index.html
  dev_url: https://github.com/Nixtla/statsforecast/

extra:
  recipe-maintainers:
    - sugatoray
    - AzulGarza
    - jmoralez
    - cchallu
    - mergenthaler
    - marcopeix
    - elephaint
    - JQGoh
    - nasaul
    - MMenchero
    - goodwanghan
